// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.API.Context;

#nullable disable

namespace Stock.API.Migrations
{
    [DbContext(typeof(SagaStockDBContext))]
    partial class SagaStockDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.API.Models.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quntity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44d4a41b-69be-49a0-a5b2-94c62f3d3a62"),
                            ProductId = new Guid("0bd39273-fcc6-4167-b1e9-88fccf9dfa2e"),
                            Quntity = 5
                        },
                        new
                        {
                            Id = new Guid("a5b3f877-8816-4f8e-ade4-ea1641b5c4a4"),
                            ProductId = new Guid("25bba58e-c7c5-4dca-ab2f-6ca0fbc98f09"),
                            Quntity = 14
                        },
                        new
                        {
                            Id = new Guid("de81ba9e-b2c7-4f01-8ab4-666f40566e7e"),
                            ProductId = new Guid("7e8e9773-2670-4e06-9115-f1e4aa8acf22"),
                            Quntity = 13
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
